
# Generated by Django 3.1.2 on 2020-11-21 15:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=200, null=True, unique=True)),
                ('balance', models.IntegerField(default=10000)),
                ('watchlist', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_ID', models.IntegerField()),
                ('expiration_date', models.DateField()),
                ('stock', models.CharField(default='', max_length=200, unique=True)),
                ('purchase_price', models.IntegerField(default=-999)),
                ('quantity', models.IntegerField(default=100)),
                ('closed', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='transaction',
            field=models.ManyToManyField(blank=True, null=True, related_name='transaction', to='app.Transaction'),
        ),
    ]
