# Generated by Django 2.1.15 on 2020-12-05 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_ID',
        ),
        migrations.AddField(
            model_name='transaction',
            name='contract_symbol',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='transaction',
            name='strike',
            field=models.IntegerField(default=-999),
        ),
        migrations.AddField(
            model_name='transaction',
            name='typ',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='expiration_date',
            field=models.CharField(default='', max_length=200),
        ),
    ]
