# Generated by Django 3.1.3 on 2020-11-23 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='date',
            new_name='expiration_date',
        ),
        migrations.AddField(
            model_name='account',
            name='watchlist',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='transaction',
            name='purchase_price',
            field=models.IntegerField(default=-999),
        ),
        migrations.AddField(
            model_name='transaction',
            name='quantity',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='transaction',
            name='stock',
            field=models.CharField(default='', max_length=200, unique=True),
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
