# Generated by Django 3.1.3 on 2020-11-23 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201123_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='transaction',
            field=models.ManyToManyField(blank=True, null=True, related_name='transaction', to='app.Transaction'),
        ),
        migrations.AlterField(
            model_name='account',
            name='watchlist',
            field=models.TextField(blank=True, default=''),
        ),
    ]
