# Generated by Django 3.1.2 on 2020-12-02 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_transaction_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='strike',
            field=models.IntegerField(default=-999),
        ),
        migrations.AddField(
            model_name='transaction',
            name='typ',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='expiration_date',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='stock',
            field=models.CharField(default='', max_length=200),
        ),
    ]
