# Generated by Django 3.1.2 on 2020-11-25 02:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_auto_20201123_2311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='expiration_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='account',
            name='watchlist',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='purchase_price',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='stock',
        ),
        migrations.AlterField(
            model_name='account',
            name='transaction',
            field=models.ManyToManyField(null=True, related_name='transaction', to='app.Transaction'),
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('transactions', models.ManyToManyField(related_name='transactions', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
