# Generated by Django 3.1.2 on 2020-12-05 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201202_0344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='stock',
        ),
        migrations.AddField(
            model_name='transaction',
            name='contract_symbol',
            field=models.CharField(default='', max_length=200, unique=True),
        ),
    ]
