# Generated by Django 3.1.2 on 2020-11-25 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201125_0231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='date',
            new_name='expiration_date',
        ),
        migrations.AddField(
            model_name='account',
            name='watchlist',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='transaction',
            name='purchase_price',
            field=models.IntegerField(default=-999),
        ),
        migrations.AddField(
            model_name='transaction',
            name='quantity',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='transaction',
            name='stock',
            field=models.CharField(default='', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='transaction',
            field=models.ManyToManyField(blank=True, null=True, related_name='transaction', to='app.Transaction'),
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
