# Generated by Django 3.1.2 on 2020-11-25 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20201125_0235'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='contract_symbol',
            field=models.CharField(default='', max_length=200, unique=True),
        ),
    ]
