# Generated by Django 3.1.2 on 2020-12-05 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20201205_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='contract_symbol',
            field=models.CharField(default='', max_length=200),
        ),
    ]
