# Generated by Django 2.1.15 on 2020-12-06 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201205_2345'),
        ('app', '0006_auto_20201205_2259'),
    ]

    operations = [
    ]
